length_of_beam = int(input("What is the length of the beam? "))
position_of_pivot = int(input("What is the position of the pivot? "))
mass_of_beam = int(input("What is the mass of the beam? "))
position_of_force = int(input("What is the position of the force"))
print("")